//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Micajah.FileService.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Micajah.FileService.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        internal static string FileList_DeleteText {
            get {
                return ResourceManager.GetString("FileList_DeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete it?.
        /// </summary>
        internal static string FileList_DeletingConfirmationText {
            get {
                return ResourceManager.GetString("FileList_DeletingConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files found..
        /// </summary>
        internal static string FileList_EmptyDataText {
            get {
                return ResourceManager.GetString("FileList_EmptyDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        internal static string FileList_FileNameText {
            get {
                return ResourceManager.GetString("FileList_FileNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string FileList_SizeText {
            get {
                return ResourceManager.GetString("FileList_SizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Modified.
        /// </summary>
        internal static string FileList_UpdatedWhenText {
            get {
                return ResourceManager.GetString("FileList_UpdatedWhenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all of these images at once.
        /// </summary>
        internal static string FileList_ViewAllAtOnceLink_Text {
            get {
                return ResourceManager.GetString("FileList_ViewAllAtOnceLink_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string ImageUpload_ButtonSeparator_Text {
            get {
                return ResourceManager.GetString("ImageUpload_ButtonSeparator_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ImageUpload_ClosePopupWindowButton_Text {
            get {
                return ResourceManager.GetString("ImageUpload_ClosePopupWindowButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not exists.
        /// </summary>
        internal static string ImageUpload_FileNotExists {
            get {
                return ResourceManager.GetString("ImageUpload_FileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path is empty.
        /// </summary>
        internal static string ImageUpload_FilePathIsEmpty {
            get {
                return ResourceManager.GetString("ImageUpload_FilePathIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file extension.
        /// </summary>
        internal static string ImageUpload_InvalidFileExtension {
            get {
                return ResourceManager.GetString("ImageUpload_InvalidFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file size.
        /// </summary>
        internal static string ImageUpload_InvalidFileSize {
            get {
                return ResourceManager.GetString("ImageUpload_InvalidFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL.
        /// </summary>
        internal static string ImageUpload_InvalidUrl {
            get {
                return ResourceManager.GetString("ImageUpload_InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Image.
        /// </summary>
        internal static string ImageUpload_NoImageLabel_Text {
            get {
                return ResourceManager.GetString("ImageUpload_NoImageLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to attach an image.
        /// </summary>
        internal static string ImageUpload_OpenLink_ToolTip {
            get {
                return ResourceManager.GetString("ImageUpload_OpenLink_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach Image.
        /// </summary>
        internal static string ImageUpload_PopupWindow_Title {
            get {
                return ResourceManager.GetString("ImageUpload_PopupWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Selected Image.
        /// </summary>
        internal static string ImageUpload_UploadButton_Text {
            get {
                return ResourceManager.GetString("ImageUpload_UploadButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a file from &lt;b&gt;my computer&lt;/b&gt;.
        /// </summary>
        internal static string ImageUpload_UploadTypeList_FromMyComputerItem_Text {
            get {
                return ResourceManager.GetString("ImageUpload_UploadTypeList_FromMyComputerItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a file from &lt;b&gt;the web&lt;/b&gt;.
        /// </summary>
        internal static string ImageUpload_UploadTypeList_FromWebItem_Text {
            get {
                return ResourceManager.GetString("ImageUpload_UploadTypeList_FromWebItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL is empty.
        /// </summary>
        internal static string ImageUpload_UrlIsEmpty {
            get {
                return ResourceManager.GetString("ImageUpload_UrlIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an invalid resource request..
        /// </summary>
        internal static string ResourceHandler_InvalidRequest {
            get {
                return ResourceManager.GetString("ResourceHandler_InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}MB for all files&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;a title=&quot;If you have Flash 9 or greater enabled and your browser doesn&apos;t have ad-blocking plug-ins installed&quot;&gt;Multi File Selector&lt;/a&gt;.
        /// </summary>
        internal static string SimpleUpload_ChangeModeToAdvanced {
            get {
                return ResourceManager.GetString("SimpleUpload_ChangeModeToAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}MB per file&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;a&gt;Single File Selector&lt;/a&gt;.
        /// </summary>
        internal static string SimpleUpload_ChangeModeToBasic {
            get {
                return ResourceManager.GetString("SimpleUpload_ChangeModeToBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file is not uploaded yet.
        /// </summary>
        internal static string SimpleUpload_FileIsNotUploadedYet {
            get {
                return ResourceManager.GetString("SimpleUpload_FileIsNotUploadedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file extension detected.
        /// </summary>
        internal static string SimpleUpload_InvalidFileExtension {
            get {
                return ResourceManager.GetString("SimpleUpload_InvalidFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file size detected.
        /// </summary>
        internal static string SimpleUpload_InvalidFileSize {
            get {
                return ResourceManager.GetString("SimpleUpload_InvalidFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MIME type detected.
        /// </summary>
        internal static string SimpleUpload_InvalidMimeType {
            get {
                return ResourceManager.GetString("SimpleUpload_InvalidMimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Files.
        /// </summary>
        internal static string SimpleUpload_OpenLink_Text {
            get {
                return ResourceManager.GetString("SimpleUpload_OpenLink_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait, file upload in progress....
        /// </summary>
        internal static string SimpleUpload_ProgressArea_Title {
            get {
                return ResourceManager.GetString("SimpleUpload_ProgressArea_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Attachments.
        /// </summary>
        internal static string SimpleUpload_Title {
            get {
                return ResourceManager.GetString("SimpleUpload_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have attempted to select too many files.
        /// </summary>
        internal static string SimpleUpload_TooManyFilesSelected {
            get {
                return ResourceManager.GetString("SimpleUpload_TooManyFilesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Files &amp; Close.
        /// </summary>
        internal static string SimpleUpload_UploadButton_Text {
            get {
                return ResourceManager.GetString("SimpleUpload_UploadButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unique identifiers of the controls which upload the selected files are not specified. Please use the UploadControlsUniqueId property to assign a value..
        /// </summary>
        internal static string SimpleUpload_UploadControlsUniqueIdNotSpecified {
            get {
                return ResourceManager.GetString("SimpleUpload_UploadControlsUniqueIdNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The control with UniqueID &apos;{0}&apos; is not found. Please check the UploadControlsUniqueId property&apos;s value..
        /// </summary>
        internal static string SimpleUpload_UploadControlUniqueIdNotFound {
            get {
                return ResourceManager.GetString("SimpleUpload_UploadControlUniqueIdNotFound", resourceCulture);
            }
        }
    }
}
