//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Micajah.FileService.Tools.UploadFilesToAzure.FileService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.bigwebapps.com/webservices/filemanager/", ConfigurationName="FileService.FileMtomServiceSoap")]
    public interface FileMtomServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bigwebapps.com/webservices/filemanager/CopyFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CopyFile(string applicationGuid, string organizationGuid, string departmentGuid, string fileId, string destinationOrganizationGuid, string destinationDepartmentGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bigwebapps.com/webservices/filemanager/GetFileInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool GetFileInfo(string fileId, ref string fullFileName, ref long fileSize, ref int width, ref int height, ref int align, ref string fileMimeType, ref string checksum);
        
        // CODEGEN: Parameter 'getFileResponse' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bigwebapps.com/webservices/filemanager/GetFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getFileResponse")]
        Micajah.FileService.Tools.UploadFilesToAzure.FileService.GetFileResponse1 GetFile(Micajah.FileService.Tools.UploadFilesToAzure.FileService.GetFileRequest request);
        
        // CODEGEN: Parameter 'getFileResponse' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bigwebapps.com/webservices/filemanager/GetThumbnail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getFileResponse")]
        Micajah.FileService.Tools.UploadFilesToAzure.FileService.GetThumbnailResponse GetThumbnail(Micajah.FileService.Tools.UploadFilesToAzure.FileService.GetThumbnailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bigwebapps.com/webservices/filemanager/DeleteFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DeleteFile(string fileId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bigwebapps.com/webservices/filemanager/GetTemporaryFiles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetTemporaryFiles(string fileGuid);
        
        // CODEGEN: Parameter 'getFileResponseStreaming' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bigwebapps.com/webservices/filemanager/PutFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Micajah.FileService.Tools.UploadFilesToAzure.FileService.PutFileResponse PutFile(Micajah.FileService.Tools.UploadFilesToAzure.FileService.PutFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bigwebapps.com/webservices/filemanager/PutFileFromUrl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string PutFileFromUrl(string applicationGuid, string organizationName, ref string organizationGuid, string departmentName, ref string departmentGuid, string fileUrl, ref string checksum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bigwebapps.com/webservices/filemanager/SetTemporaryFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SetTemporaryFile(string fileId, string fileGuid);
        
        // CODEGEN: Parameter 'getFileResponseStreaming' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bigwebapps.com/webservices/filemanager/UpdateFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Micajah.FileService.Tools.UploadFilesToAzure.FileService.UpdateFileResponse UpdateFile(Micajah.FileService.Tools.UploadFilesToAzure.FileService.UpdateFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bigwebapps.com/webservices/filemanager/UpdateFileFromUrl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateFileFromUrl(string fileId, string fileUrl, ref string checksum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.bigwebapps.com/webservices/filemanager/UpdateFileExpirationRequired", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateFileExpirationRequired(string fileId, bool expirationRequired);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bigwebapps.com/webservices/filemanager/")]
    public partial class GetFileResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fileNameField;
        
        private byte[] fileDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] fileData {
            get {
                return this.fileDataField;
            }
            set {
                this.fileDataField = value;
                this.RaisePropertyChanged("fileData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bigwebapps.com/webservices/filemanager/")]
    public partial class GetFileRequestStreaming : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fileNameField;
        
        private byte[] fileDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] fileData {
            get {
                return this.fileDataField;
            }
            set {
                this.fileDataField = value;
                this.RaisePropertyChanged("fileData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFile", WrapperNamespace="http://www.bigwebapps.com/webservices/filemanager/", IsWrapped=true)]
    public partial class GetFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.bigwebapps.com/webservices/filemanager/", Order=0)]
        public string fileId;
        
        public GetFileRequest() {
        }
        
        public GetFileRequest(string fileId) {
            this.fileId = fileId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileResponse", WrapperNamespace="http://www.bigwebapps.com/webservices/filemanager/", IsWrapped=true)]
    public partial class GetFileResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.bigwebapps.com/webservices/filemanager/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Micajah.FileService.Tools.UploadFilesToAzure.FileService.GetFileResponse getFileResponse;
        
        public GetFileResponse1() {
        }
        
        public GetFileResponse1(Micajah.FileService.Tools.UploadFilesToAzure.FileService.GetFileResponse getFileResponse) {
            this.getFileResponse = getFileResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetThumbnail", WrapperNamespace="http://www.bigwebapps.com/webservices/filemanager/", IsWrapped=true)]
    public partial class GetThumbnailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.bigwebapps.com/webservices/filemanager/", Order=0)]
        public string fileId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.bigwebapps.com/webservices/filemanager/", Order=1)]
        public int width;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.bigwebapps.com/webservices/filemanager/", Order=2)]
        public int height;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.bigwebapps.com/webservices/filemanager/", Order=3)]
        public int align;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.bigwebapps.com/webservices/filemanager/", Order=4)]
        public string result;
        
        public GetThumbnailRequest() {
        }
        
        public GetThumbnailRequest(string fileId, int width, int height, int align, string result) {
            this.fileId = fileId;
            this.width = width;
            this.height = height;
            this.align = align;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetThumbnailResponse", WrapperNamespace="http://www.bigwebapps.com/webservices/filemanager/", IsWrapped=true)]
    public partial class GetThumbnailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.bigwebapps.com/webservices/filemanager/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Micajah.FileService.Tools.UploadFilesToAzure.FileService.GetFileResponse getFileResponse;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.bigwebapps.com/webservices/filemanager/", Order=1)]
        public string result;
        
        public GetThumbnailResponse() {
        }
        
        public GetThumbnailResponse(Micajah.FileService.Tools.UploadFilesToAzure.FileService.GetFileResponse getFileResponse, string result) {
            this.getFileResponse = getFileResponse;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PutFile", WrapperNamespace="http://www.bigwebapps.com/webservices/filemanager/", IsWrapped=true)]
    public partial class PutFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.bigwebapps.com/webservices/filemanager/", Order=0)]
        public string applicationGuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.bigwebapps.com/webservices/filemanager/", Order=1)]
        public string organizationName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.bigwebapps.com/webservices/filemanager/", Order=2)]
        public string organizationGuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.bigwebapps.com/webservices/filemanager/", Order=3)]
        public string departmentName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.bigwebapps.com/webservices/filemanager/", Order=4)]
        public string departmentGuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.bigwebapps.com/webservices/filemanager/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Micajah.FileService.Tools.UploadFilesToAzure.FileService.GetFileRequestStreaming getFileResponseStreaming;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.bigwebapps.com/webservices/filemanager/", Order=6)]
        public string checksum;
        
        public PutFileRequest() {
        }
        
        public PutFileRequest(string applicationGuid, string organizationName, string organizationGuid, string departmentName, string departmentGuid, Micajah.FileService.Tools.UploadFilesToAzure.FileService.GetFileRequestStreaming getFileResponseStreaming, string checksum) {
            this.applicationGuid = applicationGuid;
            this.organizationName = organizationName;
            this.organizationGuid = organizationGuid;
            this.departmentName = departmentName;
            this.departmentGuid = departmentGuid;
            this.getFileResponseStreaming = getFileResponseStreaming;
            this.checksum = checksum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PutFileResponse", WrapperNamespace="http://www.bigwebapps.com/webservices/filemanager/", IsWrapped=true)]
    public partial class PutFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.bigwebapps.com/webservices/filemanager/", Order=0)]
        public string PutFileResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.bigwebapps.com/webservices/filemanager/", Order=1)]
        public string organizationGuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.bigwebapps.com/webservices/filemanager/", Order=2)]
        public string departmentGuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.bigwebapps.com/webservices/filemanager/", Order=3)]
        public string checksum;
        
        public PutFileResponse() {
        }
        
        public PutFileResponse(string PutFileResult, string organizationGuid, string departmentGuid, string checksum) {
            this.PutFileResult = PutFileResult;
            this.organizationGuid = organizationGuid;
            this.departmentGuid = departmentGuid;
            this.checksum = checksum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateFile", WrapperNamespace="http://www.bigwebapps.com/webservices/filemanager/", IsWrapped=true)]
    public partial class UpdateFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.bigwebapps.com/webservices/filemanager/", Order=0)]
        public string fileId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.bigwebapps.com/webservices/filemanager/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Micajah.FileService.Tools.UploadFilesToAzure.FileService.GetFileRequestStreaming getFileResponseStreaming;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.bigwebapps.com/webservices/filemanager/", Order=2)]
        public string checksum;
        
        public UpdateFileRequest() {
        }
        
        public UpdateFileRequest(string fileId, Micajah.FileService.Tools.UploadFilesToAzure.FileService.GetFileRequestStreaming getFileResponseStreaming, string checksum) {
            this.fileId = fileId;
            this.getFileResponseStreaming = getFileResponseStreaming;
            this.checksum = checksum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateFileResponse", WrapperNamespace="http://www.bigwebapps.com/webservices/filemanager/", IsWrapped=true)]
    public partial class UpdateFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.bigwebapps.com/webservices/filemanager/", Order=0)]
        public string UpdateFileResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.bigwebapps.com/webservices/filemanager/", Order=1)]
        public string checksum;
        
        public UpdateFileResponse() {
        }
        
        public UpdateFileResponse(string UpdateFileResult, string checksum) {
            this.UpdateFileResult = UpdateFileResult;
            this.checksum = checksum;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FileMtomServiceSoapChannel : Micajah.FileService.Tools.UploadFilesToAzure.FileService.FileMtomServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileMtomServiceSoapClient : System.ServiceModel.ClientBase<Micajah.FileService.Tools.UploadFilesToAzure.FileService.FileMtomServiceSoap>, Micajah.FileService.Tools.UploadFilesToAzure.FileService.FileMtomServiceSoap {
        
        public FileMtomServiceSoapClient() {
        }
        
        public FileMtomServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileMtomServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileMtomServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileMtomServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CopyFile(string applicationGuid, string organizationGuid, string departmentGuid, string fileId, string destinationOrganizationGuid, string destinationDepartmentGuid) {
            return base.Channel.CopyFile(applicationGuid, organizationGuid, departmentGuid, fileId, destinationOrganizationGuid, destinationDepartmentGuid);
        }
        
        public bool GetFileInfo(string fileId, ref string fullFileName, ref long fileSize, ref int width, ref int height, ref int align, ref string fileMimeType, ref string checksum) {
            return base.Channel.GetFileInfo(fileId, ref fullFileName, ref fileSize, ref width, ref height, ref align, ref fileMimeType, ref checksum);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Micajah.FileService.Tools.UploadFilesToAzure.FileService.GetFileResponse1 Micajah.FileService.Tools.UploadFilesToAzure.FileService.FileMtomServiceSoap.GetFile(Micajah.FileService.Tools.UploadFilesToAzure.FileService.GetFileRequest request) {
            return base.Channel.GetFile(request);
        }
        
        public Micajah.FileService.Tools.UploadFilesToAzure.FileService.GetFileResponse GetFile(string fileId) {
            Micajah.FileService.Tools.UploadFilesToAzure.FileService.GetFileRequest inValue = new Micajah.FileService.Tools.UploadFilesToAzure.FileService.GetFileRequest();
            inValue.fileId = fileId;
            Micajah.FileService.Tools.UploadFilesToAzure.FileService.GetFileResponse1 retVal = ((Micajah.FileService.Tools.UploadFilesToAzure.FileService.FileMtomServiceSoap)(this)).GetFile(inValue);
            return retVal.getFileResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Micajah.FileService.Tools.UploadFilesToAzure.FileService.GetThumbnailResponse Micajah.FileService.Tools.UploadFilesToAzure.FileService.FileMtomServiceSoap.GetThumbnail(Micajah.FileService.Tools.UploadFilesToAzure.FileService.GetThumbnailRequest request) {
            return base.Channel.GetThumbnail(request);
        }
        
        public Micajah.FileService.Tools.UploadFilesToAzure.FileService.GetFileResponse GetThumbnail(string fileId, int width, int height, int align, ref string result) {
            Micajah.FileService.Tools.UploadFilesToAzure.FileService.GetThumbnailRequest inValue = new Micajah.FileService.Tools.UploadFilesToAzure.FileService.GetThumbnailRequest();
            inValue.fileId = fileId;
            inValue.width = width;
            inValue.height = height;
            inValue.align = align;
            inValue.result = result;
            Micajah.FileService.Tools.UploadFilesToAzure.FileService.GetThumbnailResponse retVal = ((Micajah.FileService.Tools.UploadFilesToAzure.FileService.FileMtomServiceSoap)(this)).GetThumbnail(inValue);
            result = retVal.result;
            return retVal.getFileResponse;
        }
        
        public string DeleteFile(string fileId) {
            return base.Channel.DeleteFile(fileId);
        }
        
        public string GetTemporaryFiles(string fileGuid) {
            return base.Channel.GetTemporaryFiles(fileGuid);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Micajah.FileService.Tools.UploadFilesToAzure.FileService.PutFileResponse Micajah.FileService.Tools.UploadFilesToAzure.FileService.FileMtomServiceSoap.PutFile(Micajah.FileService.Tools.UploadFilesToAzure.FileService.PutFileRequest request) {
            return base.Channel.PutFile(request);
        }
        
        public string PutFile(string applicationGuid, string organizationName, ref string organizationGuid, string departmentName, ref string departmentGuid, Micajah.FileService.Tools.UploadFilesToAzure.FileService.GetFileRequestStreaming getFileResponseStreaming, ref string checksum) {
            Micajah.FileService.Tools.UploadFilesToAzure.FileService.PutFileRequest inValue = new Micajah.FileService.Tools.UploadFilesToAzure.FileService.PutFileRequest();
            inValue.applicationGuid = applicationGuid;
            inValue.organizationName = organizationName;
            inValue.organizationGuid = organizationGuid;
            inValue.departmentName = departmentName;
            inValue.departmentGuid = departmentGuid;
            inValue.getFileResponseStreaming = getFileResponseStreaming;
            inValue.checksum = checksum;
            Micajah.FileService.Tools.UploadFilesToAzure.FileService.PutFileResponse retVal = ((Micajah.FileService.Tools.UploadFilesToAzure.FileService.FileMtomServiceSoap)(this)).PutFile(inValue);
            organizationGuid = retVal.organizationGuid;
            departmentGuid = retVal.departmentGuid;
            checksum = retVal.checksum;
            return retVal.PutFileResult;
        }
        
        public string PutFileFromUrl(string applicationGuid, string organizationName, ref string organizationGuid, string departmentName, ref string departmentGuid, string fileUrl, ref string checksum) {
            return base.Channel.PutFileFromUrl(applicationGuid, organizationName, ref organizationGuid, departmentName, ref departmentGuid, fileUrl, ref checksum);
        }
        
        public string SetTemporaryFile(string fileId, string fileGuid) {
            return base.Channel.SetTemporaryFile(fileId, fileGuid);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Micajah.FileService.Tools.UploadFilesToAzure.FileService.UpdateFileResponse Micajah.FileService.Tools.UploadFilesToAzure.FileService.FileMtomServiceSoap.UpdateFile(Micajah.FileService.Tools.UploadFilesToAzure.FileService.UpdateFileRequest request) {
            return base.Channel.UpdateFile(request);
        }
        
        public string UpdateFile(string fileId, Micajah.FileService.Tools.UploadFilesToAzure.FileService.GetFileRequestStreaming getFileResponseStreaming, ref string checksum) {
            Micajah.FileService.Tools.UploadFilesToAzure.FileService.UpdateFileRequest inValue = new Micajah.FileService.Tools.UploadFilesToAzure.FileService.UpdateFileRequest();
            inValue.fileId = fileId;
            inValue.getFileResponseStreaming = getFileResponseStreaming;
            inValue.checksum = checksum;
            Micajah.FileService.Tools.UploadFilesToAzure.FileService.UpdateFileResponse retVal = ((Micajah.FileService.Tools.UploadFilesToAzure.FileService.FileMtomServiceSoap)(this)).UpdateFile(inValue);
            checksum = retVal.checksum;
            return retVal.UpdateFileResult;
        }
        
        public string UpdateFileFromUrl(string fileId, string fileUrl, ref string checksum) {
            return base.Channel.UpdateFileFromUrl(fileId, fileUrl, ref checksum);
        }
        
        public string UpdateFileExpirationRequired(string fileId, bool expirationRequired) {
            return base.Channel.UpdateFileExpirationRequired(fileId, expirationRequired);
        }
    }
}
